/*

CREATE TABLE IF NOT EXISTS IDN_RESOURCE(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  RESOURCE_ID VARCHAR(255),
  RESOURCE_NAME VARCHAR(255),
  TIME_CREATED TIMESTAMP DEFAULT '0',
  RESOUCE_OWNER_ID VARCHAR(255),
  TENANT_ID INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS IDN_RESOURCE_META_DATA (
  RESOURCE_ID VARCHAR(255) NOT NULL,
  PROPERTY_KEY VARCHAR(255),
  PROPERTY_VALUE VARCHAR(255),
  PRIMARY KEY (RESOURCE_ID),
  FOREIGN KEY (RESOURCE_ID) REFERENCES IDN_RESOURCE(RESOURCE_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS IDN_SCOPE
(
    SCOPE_ID INTEGER NOT NULL AUTO_INCREMENT,
    RESOURCE_ID   VARCHAR (255),
    NAME VARCHAR (255),
    DESCRIPTION VARCHAR (255),
    TENANT_ID INTEGER ,
    PRIMARY KEY (SCOPE_ID),
    FOREIGN KEY (RESOURCE_ID) REFERENCES IDN_RESOURCE_META_DATA(RESOURCE_ID) ON DELETE CASCADE
);*/

CREATE TABLE IDN_RESOURCE (
  ID                  INTEGER   AUTO_INCREMENT NOT NULL,
  RESOURCE_ID         VARCHAR(255),
  RESOURCE_NAME       VARCHAR(255),
  TIME_CREATED        TIMESTAMP  NOT NULL,
  RESOUCE_OWNER_ID    VARCHAR(255),
  TENANT_ID           INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE IDN_RESOURCE_SCOPE
(
  ID INTEGER AUTO_INCREMENT NOT NULL,
  FK_RESOURCE_ID INTEGER,
  SCOPE_NAME VARCHAR(255),
  PRIMARY KEY (ID),
  CONSTRAINT FK_IDN_RESOURCE FOREIGN KEY (FK_RESOURCE_ID) REFERENCES IDN_RESOURCE (ID)
);

CREATE TABLE IDN_RESOURCE_META_DATA (
  ID                INTEGER AUTO_INCREMENT NOT NULL,
  FK_RESOURCE_ID_META_DATA       INTEGER,
  PROPERTY_KEY      VARCHAR(255),
  PROPERTY_VALUE    VARCHAR(255),
  PRIMARY KEY (ID),
  CONSTRAINT FK_RESOURCE_META_DATA FOREIGN KEY (FK_RESOURCE_ID_META_DATA) REFERENCES IDN_RESOURCE (ID)
  ON DELETE CASCADE
);



