CREATE TABLE IDN_RESOURCE (
  ID                  INTEGER   AUTO_INCREMENT NOT NULL,
  RESOURCE_ID         VARCHAR(255),
  RESOURCE_NAME       VARCHAR(255),
  TIME_CREATED        TIMESTAMP  NOT NULL,
  RESOURCE_OWNER_NAME  VARCHAR(255),
  TENANT_DOMAIN          VARCHAR(255),
  CONSUMER_KEY        VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE IDN_RESOURCE_SCOPE
(
  ID INTEGER AUTO_INCREMENT NOT NULL,
  FK_RESOURCE_ID INTEGER,
  SCOPE_NAME VARCHAR(255),
  PRIMARY KEY (ID),
  CONSTRAINT FK_IDN_RESOURCE FOREIGN KEY (FK_RESOURCE_ID) REFERENCES IDN_RESOURCE (ID)
);

CREATE TABLE IDN_RESOURCE_META_DATA (
  ID                INTEGER AUTO_INCREMENT NOT NULL,
  FK_RESOURCE_ID_META_DATA       INTEGER,
  PROPERTY_KEY      VARCHAR(255),
  PROPERTY_VALUE    VARCHAR(255),
  PRIMARY KEY (ID),
  CONSTRAINT FK_RESOURCE_META_DATA FOREIGN KEY (FK_RESOURCE_ID_META_DATA) REFERENCES IDN_RESOURCE (ID)
  ON DELETE CASCADE
);




