CREATE TABLE IDN_RESOURCE_SET
(
RESOURCE_SET_ID varchar(30) PRIMARY KEY,
RESOURCE_SET_NAME VARCHAR (30),
TIME_CREATED timestamp NOT NULL,
TOKEN_ID VARCHAR NOT NULL,
RESOUCE_OWNER_ID varchar(30),
RESOURCE_SERVER_ID varchar(30),
RESOURCE_OWNER_NAME varchar(30),
ACCESS_TOKEN VARCHAR(20)
);

CREATE TABLE IDN_RESOURCE_SET_META_DATA
(
SCOPE_ID varchar(30) PRIMARY KEY,
RESOURCE_SET_ID varchar(30),
PROPERTY_KEY varchar(40),
PROPERTY_VALUE varchar(30),
CONSTRAINT FK_Resource_Meta_Data FOREIGN KEY (RESOURCE_SET_ID) REFERENCES IDN_RESOURCE_SET (RESOURCE_SET_ID)
);

CREATE TABLE IDN_RESOURCE_SET_SCOPE
(
SCOPE_ID varchar(30) PRIMARY KEY,
SCOPE_KEY varchar(30),
SCOPE_NAME varchar(30),
DESCRIPTION varchar(30),
ROLES varchar(30),
CONSTRAINT FK_Resource_set_scope FOREIGN KEY (SCOPE_ID) REFERENCES IDN_RESOURCE_SET_META_DATA (SCOPE_ID)
);

DROP TABLE IDN_RESOURCE;
DROP TABLE IDN_RESOURCE_META_DATA;
DROP TABLE IDN_RESOURCE_SCOPE;

select IDN_RESOURCE_SET.RESOURCE_SET_ID,IDN_RESOURCE_SET.RESOURCE_SET_NAME,IDN_RESOURCE_SET_META_DATA.PROPERTY_KEY,IDN_RESOURCE_SET_META_DATA.PROPERTY_VALUE,IDN_RESOURCE_SET_SCOPE.SCOPE_NAME
from (IDN_RESOURCE_SET
inner join IDN_RESOURCE_SET_META_DATA on IDN_RESOURCE_SET.RESOURCE_SET_ID = IDN_RESOURCE_SET_META_DATA.RESOURCE_SET_ID)
inner join IDN_RESOURCE_SET_SCOPE on IDN_RESOURCE_SET_META_DATA.SCOPE_ID = IDN_RESOURCE_SET_SCOPE.SCOPE_ID
where IDN_RESOURCE_SET.RESOURCE_SET_ID =11;

INSERT INTO IDN_RESOURCE_SET (RESOURCE_SET_ID, RESOURCE_SET_NAME, TIME_CREATED,TOKEN_ID,RESOUCE_OWNER_ID,
RESOURCE_SERVER_ID,RESOURCE_OWNER_NAME,ACCESS_TOKEN)
VALUES (11, photo albem,2014-07-04 11:02:04, 123,1889,server1,peter,12);

INSERT INTO IDN_RESOURCE_SET_META_DATA (SCOPE_ID, RESOURCE_SET_ID, PROPERTY_KEY, PROPERTY_VALUE)
VALUES (123,11,item_uri,flower.png);

INSERT INTO IDN_RESOURCE_SET_SCOPE(SCOPE_ID,SCOPE_KEY,SCOPE_NAME,DESCRIPTION,ROLES)
VALUES (123,abc1,view,viewing resources,Admin);





CREATE TABLE IDN_RESOURCE (
  ID                  INTEGER   AUTO_INCREMENT PRIMARY KEY NOT NULL,
  RESOURCE_ID         VARCHAR(255),
  RESOURCE_NAME       VARCHAR(255),
  TIME_CREATED        TIMESTAMP DEFAULT '0',
  TOKEN_ID            VARCHAR(255)                         NOT NULL,
  RESOUCE_OWNER_ID    VARCHAR(255),
  RESOURCE_SERVER_ID  VARCHAR(255),
  RESOURCE_OWNER_NAME VARCHAR(255),
  TENANT_ID           INTEGER
);

CREATE TABLE IDN_RESOURCE_META_DATA (
  ID                INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  RESOURCE_ID         VARCHAR(255),
  PROPERTY_KEY      VARCHAR(255),
  PROPERTY_VALUE    VARCHAR(255),
  CONSTRAINT FK_RESOURCE_META_DATA FOREIGN KEY (RESOURCE_ID) REFERENCES IDN_RESOURCE (RESOURCE_ID)
  ON DELETE CASCADE
);

/*CREATE TABLE IDN_RESOURCE_SCOPE (
  ID          INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  RESOURCE_ID VARCHAR(255),
  SCOPE_ID    INTEGER,
  CONSTRAINT FK_RESOURCE_SCOPE FOREIGN KEY (RESOURCE_ID ) REFERENCES IDN_RESOURCE (RESOURCE_ID ),
    CONSTRAINT FK_SCOPE_ID FOREIGN KEY (SCOPE_ID) REFERENCES IDN_SCOPE (SCOPE_ID)
);*/

CREATE TABLE IDN_SCOPE
(
    SCOPE_ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    RESOURCE_ID   VARCHAR (255),
    NAME VARCHAR (255),
    DESCRIPTION VARCHAR (255),
    TENANT_ID INTEGER ,
    CONSTRAINT FK_SCOPE FOREIGN KEY (RESOURCE_ID) REFERENCES IDN_RESOURCE_META_DATA (RESOURCE_ID)
    ON DELETE CASCADE
);

DROP TABLE IDN_RESOURCE;
DROP TABLE IDN_RESOURCE_META_DATA;
DROP TABLE IDN_SCOPE;


