CREATE TABLE IDN_RESOURCE (
  ID                  INTEGER   AUTO_INCREMENT PRIMARY KEY NOT NULL,
  RESOURCE_ID         VARCHAR(255),
  RESOURCE_NAME       VARCHAR(30),
  TIME_CREATED        TIMESTAMP DEFAULT '0',
  RESOURCE_OWNER_ID    VARCHAR(255),
  TENANT_ID           INTEGER
);
Drop TABLE IDN_RESOURCE;
insert into IDN_RESOURCE (
  RESOURCE_ID, RESOURCE_NAME, TIME_CREATED,  RESOURCE_OWNER_ID,
  TENANT_ID) VALUES
  ('1', 'resource1', NOW(),'1', '1');
insert into IDN_RESOURCE (
  RESOURCE_ID, RESOURCE_NAME, TIME_CREATED,  RESOURCE_OWNER_ID,
  TENANT_ID) VALUES
  ('2', 'resource2', NOW(),'2', '1');

CREATE TABLE IDN_RESOURCE_META_DATA (
  ID                INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  RESOURCE_IDENTITY INTEGER NOT NULL,
  PROPERTY_KEY      VARCHAR(40),
  PROPERTY_VALUE    VARCHAR(40),
  CONSTRAINT FK_RESOURCE_META_DATA FOREIGN KEY (RESOURCE_IDENTITY) REFERENCES IDN_RESOURCE (ID)
  ON DELETE CASCADE
);

CREATE TABLE IDN_RESOURCE_SCOPE
(
  ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  RESOURCE_IDENTITY INTEGER NOT NULL ,
  SCOPE_NAME VARCHAR(255),
  CONSTRAINT FK_IDN_RESOURCE FOREIGN KEY (RESOURCE_IDENTITY) REFERENCES IDN_RESOURCE (ID)
  ON DELETE CASCADE
);
INSERT INTO IDN_RESOURCE_SCOPE (RESOURCE_IDENTITY, SCOPE_NAME) VALUES
  ((SELECT ID FROM IDN_RESOURCE WHERE RESOURCE_ID= '1'), 'scope1')
;
INSERT INTO IDN_RESOURCE_SCOPE (RESOURCE_IDENTITY, SCOPE_NAME) VALUES
  ((SELECT ID FROM IDN_RESOURCE WHERE RESOURCE_ID= '2'), 'scope2')
;
INSERT INTO IDN_RESOURCE_SCOPE (RESOURCE_IDENTITY, SCOPE_NAME) VALUES
  ((SELECT ID FROM IDN_RESOURCE WHERE RESOURCE_ID= '2'), 'scope22')
;

CREATE TABLE IDN_PERMISSION_TICKET (
  ID              INTEGER     AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PT              VARCHAR(255)                           NOT NULL,
  TIME_CREATED    TIMESTAMP   DEFAULT '0',
  VALIDITY_PERIOD BIGINT,
  TICKET_STATE    VARCHAR(25) DEFAULT 'ACTIVE',
  TENANT_ID	  INTEGER
);


CREATE TABLE IDN_PT_RESOURCE (
  ID       INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PT_RESOURCE_ID INTEGER NOT NULL ,
  PT_ID    INTEGER NOT NULL ,
  CONSTRAINT FK_PT FOREIGN KEY (PT_ID) REFERENCES IDN_PERMISSION_TICKET (ID) ON DELETE CASCADE,
  CONSTRAINT FK_PT_RESOURCE FOREIGN KEY (PT_RESOURCE_ID) REFERENCES IDN_RESOURCE (ID) ON DELETE CASCADE
);



CREATE TABLE IDN_PT_RESOURCE_SCOPE (
  ID          INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  PT_RESOURCE_ID INTEGER NOT NULL ,
  PT_SCOPE_ID    INTEGER NOT NULL ,
  CONSTRAINT FK_PT_RESOURCE_ID FOREIGN KEY (PT_RESOURCE_ID) REFERENCES IDN_PT_RESOURCE (ID) ON DELETE CASCADE,
  CONSTRAINT FK_PT_SCOPE_ID FOREIGN KEY (PT_SCOPE_ID) REFERENCES IDN_RESOURCE_SCOPE (ID) ON DELETE CASCADE
);
DROP TABLE IDN_PT_RESOURCE_SCOPE;